module.exports = {
    formHead: {
        fontSize: 30,
        color: 'black',
        textAlign: 'center',
        fontWeight: 'bold',
        marginTop:10,
        // backgroundColor: 'white',
    },
    formInput: {
        width: '80%',
        // height: 40,
        backgroundColor: 'white',
        borderRadius: 10,
        marginVertical: 10,
        borderWidth: 3,
        borderColor:'black',
        paddingHorizontal: 15,
        paddingVertical: 10,
        fontSize: 18,
    },
    formbtn: {
        width: '80%',
        backgroundColor: 'white',
        borderRadius: 10,
        borderColor: 'black',
        borderWidth: 3,
        fontSize: 25,
        color: 'black',
        textAlign: 'center',
        paddingVertical: 10,
        marginVertical: 10,
    },
    formTextLinkRight: {
        color: 'black',
        fontSize: 15,
        textAlign: 'right',
        width: '80%',
        marginVertical: 10,
    },
    formTextLinkCenter: {
        color: 'black',
        fontSize: 16,
    },
    formHead2: {
        fontSize: 20,
        color: 'black',
        textAlign: 'center',
        // fontWeight: 'bold',
        // backgroundColor: 'white',
    },
    formHead3: {
        fontSize: 20,
        // backgroundColor: 'white',
        color: 'black',
        textAlign: 'center',
        fontWeight: '400',
        padding: 10,
        borderRadius: 10,
        width: '80%',
        marginVertical: 10,
    },
}